# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Giordano Alvari 
user_description: My name is Giordano, a data scientist with a background in bioinformatics. I really enjoy explore and getting insight from data. Even if I started as a computational biologist working with genomic data, in the last few years I started to investigate other fields, such as business and social problems. I am fluent both in python and R. Please take a look of some of my projects!

user_title: Data Scientist
email: giordano.alvari@gmail.com
twitter_username: giordan66345162
github_username:  Dhonveli
gplus_username:  giordano.alvari

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
